#!/bin/sh
#
# A command line utility to interface with Vengit SBrick and SBrick Plus.
#

if [ -e /dev/cu.usbmodem1 ]; then
	ARGS="${ARGS} -ble112 /dev/cu.usbmodem1"
elif [ -e /dev/ttyACM0 ]; then
	ARGS="${ARGS} -ble112 /dev/ttyACM0"
fi

java -cp target/lego-wedo-java-*-fatjar.jar org.kjkoster.wedo.SBrick ${ARGS} ${*}
